openapi: 3.0.3
info:
  title: ITM TA3 API
  description: |-
    This is the specification of the TA3 API for In The Moment (ITM).  Currently, the Evaluation API for TA2 supports functionality for the September milestone.

    The API is based on the OpenAPI 3.0 specification.
  version: 0.2.2
servers:
- url: /
tags:
- name: itm-ta2-eval
  description: Endpoints for TA2 Evaluation
paths:
  /ta2/startSession:
    get:
      tags:
      - itm-ta2-eval
      summary: Start a new session
      description: Get unique session id for grouping answers from a collection of
        scenarios/probes together
      operationId: start_session
      parameters:
      - name: adm_name
        in: query
        description: A self-assigned ADM name.  Can add authentication later.
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: session_type
        in: query
        description: "the type of session to start (`test`, `eval`, or a TA1 name)"
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: test
      - name: kdma_training
        in: query
        description: whether or not this is a training session with TA2
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      - name: max_scenarios
        in: query
        description: "the maximum number of scenarios requested, supported only in\
          \ `test` sessions"
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int16
      responses:
        "200":
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                description: a new session Id to use in subsequent calls
                x-content-type: text/plain
        "400":
          description: Invalid session type or max_scenarios
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "503":
          description: The server is not ready to start a session
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
  /ta2/scenario:
    get:
      tags:
      - itm-ta2-eval
      summary: Get the next scenario
      description: "Get the next scenario in a session with the specified ADM name,\
        \ returning a Scenario object and unique id"
      operationId: start_scenario
      parameters:
      - name: session_id
        in: query
        description: "a unique session_id, as returned by /ta2/startSession"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: scenario_id
        in: query
        description: "a scenario id to start, used internally by TA3"
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: "Successful operation; scenario data returned, or session_complete\
            \ is True"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        "403":
          description: Specifying a scenario ID is unauthorized
        "404":
          description: Session or Scenario ID not found
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
  /ta2/getAlignmentTarget:
    get:
      tags:
      - itm-ta2-eval
      summary: Retrieve alignment target for the scenario
      description: Retrieve alignment target for the scenario with the specified id
      operationId: get_alignment_target
      parameters:
      - name: session_id
        in: query
        description: "a unique session_id, as returned by /ta2/startSession"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: scenario_id
        in: query
        description: The ID of the scenario for which to retrieve alignment target
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: "Successful operation, alignment target returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlignmentTarget'
        "400":
          description: Scenario Complete
        "404":
          description: Session or Scenario ID not found
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
  /ta2/{scenario_id}/getState:
    get:
      tags:
      - itm-ta2-eval
      summary: Retrieve scenario state
      description: Retrieve state of the scenario with the specified id
      operationId: get_scenario_state
      parameters:
      - name: session_id
        in: query
        description: "a unique session_id, as returned by /ta2/startSession"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: scenario_id
        in: path
        description: the ID of the scenario for which to retrieve status
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: "Successful operation, scenario state returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
        "404":
          description: Invalid scenario ID supplied
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
  /ta2/{scenario_id}/getAvailableActions:
    get:
      tags:
      - itm-ta2-eval
      summary: Get a list of currently available ADM actions
      description: Retrieve a list of currently available actions in the scenario
        with the specified id
      operationId: get_available_actions
      parameters:
      - name: session_id
        in: query
        description: "a unique session_id, as returned by /ta2/startSession"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: scenario_id
        in: path
        description: The ID of the scenario for which to retrieve avaialble actions
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation; array of possible Actions returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
                x-content-type: application/json
        "400":
          description: Scenario Complete
        "404":
          description: Invalid scenario ID supplied
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
  /ta2/takeAction:
    post:
      tags:
      - itm-ta2-eval
      summary: Take an action within a scenario
      description: Take the specified Action within a scenario
      operationId: take_action
      parameters:
      - name: session_id
        in: query
        description: "a unique session_id, as returned by /ta2/startSession"
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        description: Encapsulation of an action taken by a DM in the context of the
          scenario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        "200":
          description: "Successful operation, scenario state returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
        "400":
          description: Invalid action or session_id
        "500":
          description: An exception occurred on the server; see returned error string.
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
      x-openapi-router-controller: swagger_server.controllers.itm_ta2_eval_controller
components:
  schemas:
    Scenario:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          description: a globally unique id for the scenario
          default: "1234"
        name:
          type: string
          description: "human-readable scenario name, not necessarily unique"
          example: IED Explosion
        session_complete:
          type: boolean
          description: "set to true if the session is complete; that is, there are\
            \ no more scenarios"
          example: false
        start_time:
          type: string
          description: "the wall clock local start time of the scenario, expressed\
            \ as hh:mm"
          example: 14:02
        state:
          $ref: '#/components/schemas/State'
        triage_categories:
          type: array
          items:
            $ref: '#/components/schemas/TriageCategory'
      description: a tactical scenario
      example:
        start_time: 14:02
        session_complete: false
        name: IED Explosion
        id: "1234"
        state:
          mission:
            unstructured: Place sensors in and around the jungle base
            mission_type: Listening/Observation
          environment:
            visibility: 0.5
            aid_delay: 40
            fauna: "many insects, some amphibians and reptiles"
            flora: lush jungle vegetation
            lighting: 0.7
            noise_peak: 0.8
            noise_ambient: 0.5
            unstructured: unstructured
            weather: rainy
            temperature: 82.5
            humidity: 80
            location: jungle
            terrain: dense forest with a nearby rocky streambed
            soundscape: burbling brook punctuated by enemy gunfire
          supplies:
          - quantity: 4
            type: Tourniquet
          - quantity: 4
            type: Tourniquet
          unstructured: unstructured
          elapsed_time: 5.2
          threat_state:
            unstructured: No additional threats are detected
            threats:
            - type: Gunfire
              severity: 0.5
            - type: Gunfire
              severity: 0.5
          scenario_complete: false
          casualties:
          - injuries:
            - severity: 0.8
              name: Laceration
              location: right forearm
            - severity: 0.8
              name: Laceration
              location: right forearm
            unstructured: unstructured
            name: Mary
            visited: false
            id: id
            tag: DELAYED
            relationship: NONE
            vitals:
              breathing: NORMAL
              conscious: true
              mental_status: CALM
              hrpmin: 150
            demographics:
              sex: F
              rank: Marine
              age: 32
          - injuries:
            - severity: 0.8
              name: Laceration
              location: right forearm
            - severity: 0.8
              name: Laceration
              location: right forearm
            unstructured: unstructured
            name: Mary
            visited: false
            id: id
            tag: DELAYED
            relationship: NONE
            vitals:
              breathing: NORMAL
              conscious: true
              mental_status: CALM
              hrpmin: 150
            demographics:
              sex: F
              rank: Marine
              age: 32
        triage_categories:
        - criteria: criteria
          description: description
          tagLabel: MINIMAL
        - criteria: criteria
          description: description
          tagLabel: MINIMAL
    AlignmentTarget:
      required:
      - id
      - kdma_values
      type: object
      properties:
        id:
          type: string
          description: globally unique alignment target id
        kdma_values:
          type: array
          description: list of KDMAs to align to
          items:
            $ref: '#/components/schemas/KDMA_Value'
      description: list of KDMAs to align to
      example:
        kdma_values:
        - value: 0.8
          kdma: mission
        - value: 0.8
          kdma: mission
        id: id
    KDMA_Value:
      required:
      - kdma
      - value
      type: object
      properties:
        kdma:
          type: string
          description: KDMA name
          example: mission
        value:
          type: number
          description: target alignment value
          format: float
          example: 0.8
      description: a KDMA and its value
      example:
        value: 0.8
        kdma: mission
    State:
      required:
      - unstructured
      type: object
      properties:
        unstructured:
          type: string
          description: text description of current state
        elapsed_time:
          type: number
          description: the elapsed time (in minutes) since the scenario started
          example: 5.2
        scenario_complete:
          type: boolean
          description: set to true if the scenario is complete; subsequent calls to
            /scenario/probe will return an error code
          example: false
        mission:
          $ref: '#/components/schemas/Mission'
        environment:
          $ref: '#/components/schemas/Environment'
        threat_state:
          $ref: '#/components/schemas/ThreatState'
        supplies:
          type: array
          description: a list of medical supplies available to the DM
          items:
            $ref: '#/components/schemas/Supplies'
        casualties:
          type: array
          description: the list of casualties in the scenario
          items:
            $ref: '#/components/schemas/Casualty'
      description: the current tactical & environmental state of the scenario and
        of its casualties.
      example:
        mission:
          unstructured: Place sensors in and around the jungle base
          mission_type: Listening/Observation
        environment:
          visibility: 0.5
          aid_delay: 40
          fauna: "many insects, some amphibians and reptiles"
          flora: lush jungle vegetation
          lighting: 0.7
          noise_peak: 0.8
          noise_ambient: 0.5
          unstructured: unstructured
          weather: rainy
          temperature: 82.5
          humidity: 80
          location: jungle
          terrain: dense forest with a nearby rocky streambed
          soundscape: burbling brook punctuated by enemy gunfire
        supplies:
        - quantity: 4
          type: Tourniquet
        - quantity: 4
          type: Tourniquet
        unstructured: unstructured
        elapsed_time: 5.2
        threat_state:
          unstructured: No additional threats are detected
          threats:
          - type: Gunfire
            severity: 0.5
          - type: Gunfire
            severity: 0.5
        scenario_complete: false
        casualties:
        - injuries:
          - severity: 0.8
            name: Laceration
            location: right forearm
          - severity: 0.8
            name: Laceration
            location: right forearm
          unstructured: unstructured
          name: Mary
          visited: false
          id: id
          tag: DELAYED
          relationship: NONE
          vitals:
            breathing: NORMAL
            conscious: true
            mental_status: CALM
            hrpmin: 150
          demographics:
            sex: F
            rank: Marine
            age: 32
        - injuries:
          - severity: 0.8
            name: Laceration
            location: right forearm
          - severity: 0.8
            name: Laceration
            location: right forearm
          unstructured: unstructured
          name: Mary
          visited: false
          id: id
          tag: DELAYED
          relationship: NONE
          vitals:
            breathing: NORMAL
            conscious: true
            mental_status: CALM
            hrpmin: 150
          demographics:
            sex: F
            rank: Marine
            age: 32
    Mission:
      required:
      - mission_type
      - unstructured
      type: object
      properties:
        unstructured:
          type: string
          description: natural language description of current mission
          example: Place sensors in and around the jungle base
        mission_type:
          type: string
          description: enumeration of possible mission types
          enum:
          - Listening/Observation
          - Direct Action
          - Hostage rescue
          - Asset transport
          - Sensor emplacement
          - Intelligence gathering
          - Civil affairs
          - Training
          - Sabotage
          - Security patrol
          - Fire support
          - Nuclear deterrence
          - Extraction
          - Unknown
      description: encapsulates the scenario's strategic mission
      example:
        unstructured: Place sensors in and around the jungle base
        mission_type: Listening/Observation
    Environment:
      required:
      - unstructured
      type: object
      properties:
        unstructured:
          type: string
          description: a natural language description of the environment
        weather:
          type: string
          description: a natural language description of local weather conditions
          example: rainy
        location:
          type: string
          description: a natural language description of where the scenario takes
            place
          example: jungle
        terrain:
          type: string
          description: a natural language description of the local terrain
          example: dense forest with a nearby rocky streambed
        flora:
          type: string
          description: a natural language description of the local flora
          example: lush jungle vegetation
        fauna:
          type: string
          description: a natural language description of the local fauna
          example: "many insects, some amphibians and reptiles"
        soundscape:
          type: string
          description: a natural language description of the local soundscape
          example: burbling brook punctuated by enemy gunfire
        aid_delay:
          type: number
          description: "time until tactical evacuation or exfiltration, in minutes"
          example: 40
        temperature:
          type: number
          description: numerical temperature in degrees Fahrenheit
          example: 82.5
        humidity:
          type: number
          description: percentage of relative humidity
          example: 80
        lighting:
          type: number
          description: an numeric indicator (0-1) of current lighting conditions (natural
            or man-made); lower is darker
          example: 0.7
        visibility:
          type: number
          description: "an numeric indicator (0-1) of current visibility conditions;\
            \ lower is darker. Affected by time of day, lighting, weather, terrain,\
            \ etc."
          example: 0.5
        noise_ambient:
          type: number
          description: an numeric indicator (0-1) of ambient noise at the scenario
            location; higher is louder
          example: 0.5
        noise_peak:
          type: number
          description: an numeric indicator (0-1) of peak noise at the scenario location;
            higher is louder
          example: 0.8
      description: an encapsulation of environmental factors at the scenario location
      example:
        visibility: 0.5
        aid_delay: 40
        fauna: "many insects, some amphibians and reptiles"
        flora: lush jungle vegetation
        lighting: 0.7
        noise_peak: 0.8
        noise_ambient: 0.5
        unstructured: unstructured
        weather: rainy
        temperature: 82.5
        humidity: 80
        location: jungle
        terrain: dense forest with a nearby rocky streambed
        soundscape: burbling brook punctuated by enemy gunfire
    ThreatState:
      required:
      - unstructured
      type: object
      properties:
        unstructured:
          type: string
          description: text description of current threat state
          example: No additional threats are detected
        threats:
          type: array
          description: An array of threats
          items:
            $ref: '#/components/schemas/Threat'
      description: encapsulation of the state of threat for participants in the scenario
      example:
        unstructured: No additional threats are detected
        threats:
        - type: Gunfire
          severity: 0.5
        - type: Gunfire
          severity: 0.5
    Threat:
      type: object
      additionalProperties:
        type: string
      description: |-
        list of pairs of type (enum like IED, Gunshots, fire, etc)
        and severity (float 0 (no threat) - 1 (max severity))
      example:
        type: Gunfire
        severity: 0.5
    Supplies:
      required:
      - quantity
      - type
      type: object
      properties:
        type:
          type: string
          description: an enumeration of available supply types
          example: Tourniquet
          enum:
          - Tourniquet
          - Pressure bandage
          - Hemostatic gauze
          - Decompression Needle
          - Nasopharyngeal airway
        quantity:
          type: integer
          description: the number (count) of this item available to the medic at the
            present time
          format: int32
          example: 4
      description: a single type of medical supply available to the medic
      example:
        quantity: 4
        type: Tourniquet
    Casualty:
      required:
      - id
      - unstructured
      type: object
      properties:
        id:
          type: string
          description: "string, globally unique casualty identifier"
        unstructured:
          type: string
          description: natural language text description of the casualty
        name:
          type: string
          description: "the name of the casualty, omit if unknown"
          example: Mary
        relationship:
          type: string
          description: the relationship between the medic and the casualty
          example: NONE
          enum:
          - NONE
          - ALLY
          - FRIEND
          - HOSTILE
          - EXPECTANT
        demographics:
          $ref: '#/components/schemas/Demographics'
        injuries:
          type: array
          description: an array of casualty injuries
          items:
            $ref: '#/components/schemas/Injury'
        vitals:
          $ref: '#/components/schemas/Vitals'
        visited:
          type: boolean
          description: whether or not this casualty has been visited in the current
            scenario
          default: false
        tag:
          type: string
          description: "the tag assigned to this casualty, omit if untagged"
          example: DELAYED
          enum:
          - MINIMAL
          - DELAYED
          - IMMEDIATE
          - EXPECTANT
      description: encapulation of a single casualty in the scenario
      example:
        injuries:
        - severity: 0.8
          name: Laceration
          location: right forearm
        - severity: 0.8
          name: Laceration
          location: right forearm
        unstructured: unstructured
        name: Mary
        visited: false
        id: id
        tag: DELAYED
        relationship: NONE
        vitals:
          breathing: NORMAL
          conscious: true
          mental_status: CALM
          hrpmin: 150
        demographics:
          sex: F
          rank: Marine
          age: 32
    Demographics:
      type: object
      properties:
        age:
          type: integer
          description: "the age of the casualty, omit if unknown"
          format: int16
          example: 32
        sex:
          type: string
          description: "the sex of the casualty, omit if unknown/indeterminate"
          example: F
          enum:
          - M
          - F
        rank:
          type: string
          description: "The military status of the casualty, omit if unknown"
          enum:
          - Marine
          - FMF Corpsman
          - Sailor
          - Civilian
          - SEAL
          - Intel Officer
      description: demographic profile of a casualty
      example:
        sex: F
        rank: Marine
        age: 32
    Injury:
      required:
      - location
      - name
      type: object
      properties:
        name:
          type: string
          description: a brief label for the type of injury
          example: Laceration
          enum:
          - Forehead Scrape
          - Ear Bleed
          - Asthmatic
          - Laceration
          - Puncture
          - Shrapnel
          - Chest Collapse
          - Amputation
          - Burn
        location:
          type: string
          description: the injury location on the casualty's body
          example: right forearm
          enum:
          - right forearm
          - left forearm
          - right calf
          - left calf
          - right thigh
          - left thigh
          - right stomach
          - left stomach
          - right bicep
          - left bicep
          - right shoulder
          - left shoulder
          - right side
          - left side
          - right chest
          - left chest
          - right wrist
          - left wrist
          - left face
          - right face
          - left neck
          - right neck
          - unspecified
        severity:
          type: number
          description: the apparent severity of the injury from 0 (low) to 1.0 (high)
          example: 0.8
      description: An injury on a casualty. The name field defines a controlled vocabulary.
      example:
        severity: 0.8
        name: Laceration
        location: right forearm
    Vitals:
      type: object
      properties:
        conscious:
          type: boolean
          description: whether or not the casualty is conscious
          example: true
        mental_status:
          type: string
          description: description of the casualty's overall demeanor
          example: CALM
          enum:
          - AGONY
          - CALM
          - CONFUSED
          - UPSET
          - UNRESPONSIVE
        breathing:
          type: string
          description: a descriptor for the casualty's breathing
          example: NORMAL
          enum:
          - NORMAL
          - FAST
          - RESTRICTED
          - NONE
        hrpmin:
          type: integer
          description: heart rate in beats per minute
          format: int16
          example: 150
      description: "vital levels for a casualty, omit properties if unknown"
      example:
        breathing: NORMAL
        conscious: true
        mental_status: CALM
        hrpmin: 150
    TriageCategory:
      type: object
      properties:
        tagLabel:
          type: string
          example: MINIMAL
          enum:
          - MINIMAL
          - DELAYED
          - IMMEDIATE
          - EXPECTANT
        description:
          type: string
          description: a one-line description of the tagLabel category
        criteria:
          type: string
          description: detailed criteria for the tagLabel category
      description: The type of supported triage categories for this scenario
      example:
        criteria: criteria
        description: description
        tagLabel: MINIMAL
    Action:
      required:
      - action_id
      - action_type
      - scenario_id
      type: object
      properties:
        action_id:
          type: string
          description: action ID
        scenario_id:
          type: string
          description: scenario ID this probe is for
        action_type:
          type: string
          description: The action type taken from a controlled vocabulary
          example: APPLY_TREATMENT
          enum:
          - APPLY_TREATMENT
          - CHECK_ALL_VITALS
          - CHECK_PULSE
          - CHECK_RESPIRATION
          - DIRECT_MOBILE_CASUALTIES
          - MOVE_TO_EVAC
          - SITREP
          - TAG_CASUALTY
        casualty_id:
          type: string
          description: The ID of the casualty being acted upon
        unstructured:
          type: string
          description: a plain text unstructured description of the action
          example: "Check pulse of casualty [1234]."
        justification:
          type: string
          description: A justification of the action taken
          example: Casualty is the VIP of the scenario
        kdma_association:
          type: object
          additionalProperties:
            type: string
          description: KDML associations with this action used in training
          example:
          - Mission: 0.8
        parameters:
          type: object
          additionalProperties:
            type: string
          description: key-value pairs containing additional action-specific parameters
          example:
          - treatment: Tourniquet
          - location: right forearm
      description: An encapulation of a single action taken by a DM
      example:
        action_id: action_id
        action_type: APPLY_TREATMENT
        casualty_id: casualty_id
        unstructured: "Check pulse of casualty [1234]."
        kdma_association:
        - Mission: 0.8
        justification: Casualty is the VIP of the scenario
        parameters:
        - treatment: Tourniquet
        - location: right forearm
        scenario_id: scenario_id
  responses:
    server_error:
      description: An exception occurred on the server; see returned error string.
      content:
        text/plain:
          schema:
            type: string
            x-content-type: text/plain
    state_returned:
      description: "Successful operation, scenario state returned"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/State'

